#Randomforest
library(randomForest) 

#Train Randomforest
Train_rf_model <- randomForest(DailyRelativeGrowthAdvantages ~ AntigenicDistanceABS + ChangeACE2binding + ChangeCellEntry + ChangeImmuneEscape + InfectionProportion , data = TrainingData, ntree = 500)
predictions <- predict(Train_rf_model, newdata = TrainingData)
data <- data.frame(Actual = TrainingData[,"DailyRelativeGrowthAdvantages"], Predicted = predictions, VOC = TrainingData[,"VOC"]) 
ggplot(data,aes(Actual,predictions))+geom_point()+ stat_smooth(method = lm, level = 0.99)+ stat_cor(method = "pearson")

#Test Randomforest
predictions <- predict(Train_rf_model, newdata = TestData)
data <- data.frame(Actual = TestData[,"DailyRelativeGrowthAdvantages"], Predicted = predictions, VOC = TestData[,"VOC"]) 
ggplot(data,aes(Actual,predictions))+geom_point()+ stat_smooth(method = lm, level = 0.99)+ stat_cor(method = "pearson")

#Predict the next VOC
WT_Dataset <- TrainingData %>% filter(VOC=="WT")
WT_Test <- CompareToPreVOCData_Seqs_PreProp %>% filter(VOC=="WT")
WT_rf_model <- randomForest(DailyRelativeGrowthAdvantages ~ AntigenicDistanceABS + ChangeACE2binding + ChangeCellEntry + ChangeImmuneEscape + InfectionProportion , data = WT_Dataset, ntree = 500)
WT_predictions <- predict(WT_rf_model, newdata = WT_Test)
data <- data.frame(Actual = WT_Test[,"DailyRelativeGrowthAdvantages"], Predicted = WT_predictions) 
same_sign <- (data$Actual > 0 & data$Predicted > 0) | (data$Actual < 0 & data$Predicted < 0)
proportion_same_sign <- mean(same_sign)
print(paste("WT Accuracy", proportion_same_sign))
P_WT <- ggplot(data,aes(Actual,Predicted))+geom_point()+ stat_smooth(method = lm, level = 0.99)+ stat_cor(method = "pearson")

Alpha_Dataset <- TrainingData %>% filter(VOC=="Alpha")
Alpha_Test <- CompareToPreVOCData_Seqs_PreProp %>% filter(VOC=="Alpha")
Alpha_rf_model <- randomForest(DailyRelativeGrowthAdvantages ~ AntigenicDistanceABS + ChangeACE2binding + ChangeCellEntry + ChangeImmuneEscape + InfectionProportion , data = Alpha_Dataset, ntree = 500)
Alpha_predictions <- predict(Alpha_rf_model, newdata = Alpha_Test)
data <- data.frame(Actual = Alpha_Test[,"DailyRelativeGrowthAdvantages"], Predicted = Alpha_predictions) 
same_sign <- (data$Actual > 0 & data$Predicted > 0) | (data$Actual < 0 & data$Predicted < 0)
proportion_same_sign <- mean(same_sign)
print(paste("Alpha Accuracy", proportion_same_sign))
P_Alpha <- ggplot(data,aes(Actual,Predicted))+geom_point()+ stat_smooth(method = lm, level = 0.99)+ stat_cor(method = "pearson")

Delta_Dataset <- TrainingData %>% filter(VOC=="Delta")
Delta_Test <- CompareToPreVOCData_Seqs_PreProp %>% filter(VOC=="Delta")
Delta_rf_model <- randomForest(DailyRelativeGrowthAdvantages ~ AntigenicDistanceABS + ChangeACE2binding + ChangeCellEntry + ChangeImmuneEscape + InfectionProportion , data = Delta_Dataset, ntree = 500)
Delta_predictions <- predict(Delta_rf_model, newdata = Delta_Test)
data <- data.frame(Actual = Delta_Test[,"DailyRelativeGrowthAdvantages"], Predicted = Delta_predictions) 
same_sign <- (data$Actual > 0 & data$Predicted > 0) | (data$Actual < 0 & data$Predicted < 0)
proportion_same_sign <- mean(same_sign)
print(paste("Delta Accuracy", proportion_same_sign))
P_Delta <- ggplot(data,aes(Actual,Predicted))+geom_point()+ stat_smooth(method = lm, level = 0.99)+ stat_cor(method = "pearson")

BA1_Dataset <- TrainingData %>% filter(VOC=="BA.1")
BA1_Test <- CompareToPreVOCData_Seqs_PreProp %>% filter(VOC=="BA.1")
BA1_rf_model <- randomForest(DailyRelativeGrowthAdvantages ~ AntigenicDistanceABS + ChangeACE2binding + ChangeCellEntry + ChangeImmuneEscape + InfectionProportion , data = BA1_Dataset, ntree = 500)
BA1_predictions <- predict(BA1_rf_model, newdata = BA1_Test)
data <- data.frame(Actual = BA1_Test[,"DailyRelativeGrowthAdvantages"], Predicted = BA1_predictions) 
same_sign <- (data$Actual > 0 & data$Predicted > 0) | (data$Actual < 0 & data$Predicted < 0)
proportion_same_sign <- mean(same_sign)
print(paste("BA1 Accuracy", proportion_same_sign))
P_BA1 <- ggplot(data,aes(Actual,Predicted))+geom_point()+ stat_smooth(method = lm, level = 0.99)+ stat_cor(method = "pearson")

BA2_Dataset <- TrainingData %>% filter(VOC=="BA.2")
BA2_Test <- CompareToPreVOCData_Seqs_PreProp %>% filter(VOC=="BA.2")
BA2_rf_model <- randomForest(DailyRelativeGrowthAdvantages ~ AntigenicDistanceABS + ChangeACE2binding + ChangeCellEntry + ChangeImmuneEscape + InfectionProportion , data = BA2_Dataset, ntree = 500)
BA2_predictions <- predict(BA2_rf_model, newdata = BA2_Test)
data <- data.frame(Actual = BA2_Test[,"DailyRelativeGrowthAdvantages"], Predicted = BA2_predictions) 
same_sign <- (data$Actual > 0 & data$Predicted > 0) | (data$Actual < 0 & data$Predicted < 0)
proportion_same_sign <- mean(same_sign)
print(paste("BA2 Accuracy", proportion_same_sign))
P_BA2 <- ggplot(data,aes(Actual,Predicted))+geom_point()+ stat_smooth(method = lm, level = 0.99)+ stat_cor(method = "pearson")

BA45_Dataset <- TrainingData %>% filter(VOC=="BA.4/5")
BA45_Test <- CompareToPreVOCData_Seqs_PreProp %>% filter(VOC=="BA.4/5")
BA45_rf_model <- randomForest(DailyRelativeGrowthAdvantages ~ AntigenicDistanceABS + ChangeACE2binding + ChangeCellEntry + ChangeImmuneEscape + InfectionProportion , data = BA45_Dataset, ntree = 500)
BA45_predictions <- predict(BA45_rf_model, newdata = BA45_Test)
data <- data.frame(Actual = BA45_Test[,"DailyRelativeGrowthAdvantages"], Predicted = BA45_predictions) 
same_sign <- (data$Actual > 0 & data$Predicted > 0) | (data$Actual < 0 & data$Predicted < 0)
proportion_same_sign <- mean(same_sign)
print(paste("BA45 Accuracy", proportion_same_sign))
P_BA45 <- ggplot(data,aes(Actual,Predicted))+geom_point()+ stat_smooth(method = lm, level = 0.99)+ stat_cor(method = "pearson")

BQ1_Dataset <- TrainingData %>% filter(VOC=="BQ.1")
BQ1_Test <- CompareToPreVOCData_Seqs_PreProp %>% filter(VOC=="BQ.1")
BQ1_rf_model <- randomForest(DailyRelativeGrowthAdvantages ~ AntigenicDistanceABS + ChangeACE2binding + ChangeCellEntry + ChangeImmuneEscape + InfectionProportion , data = BQ1_Dataset, ntree = 500)
BQ1_predictions <- predict(BQ1_rf_model, newdata = BQ1_Test)
data <- data.frame(Actual = BQ1_Test[,"DailyRelativeGrowthAdvantages"], Predicted = BQ1_predictions) 
same_sign <- (data$Actual > 0 & data$Predicted > 0) | (data$Actual < 0 & data$Predicted < 0)
proportion_same_sign <- mean(same_sign)
print(paste("BQ1 Accuracy", proportion_same_sign))
P_BQ1 <- ggplot(data,aes(Actual,Predicted))+geom_point()+ stat_smooth(method = lm, level = 0.99)+ stat_cor(method = "pearson")

cowplot::plot_grid(P_WT,P_Alpha,P_Delta,P_BA1,P_BA2,P_BA45,P_BQ1,ncol = 4)

